# Generated by Django 5.1.2 on 2024-11-13 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0003_listing_created_at_listing_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="state",
            field=models.CharField(
                choices=[("ACTIVE", "Active"), ("CLOSED", "Closed")],
                default="ACTIVE",
                max_length=10,
            ),
        ),
    ]
