# Generated by Django 5.1.2 on 2024-11-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0006_listing_current_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="current_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
