# Generated by Django 5.1.2 on 2024-11-15 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0008_category_listing_categories_comment_watchlist"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["category"], "verbose_name_plural": "Categories"},
        ),
        migrations.AlterField(
            model_name="category",
            name="category",
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
    ]
