# Generated by Django 5.1.2 on 2024-11-15 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0009_alter_category_options_alter_category_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["name"], "verbose_name_plural": "Categories"},
        ),
        migrations.RenameField(
            model_name="category",
            old_name="category",
            new_name="name",
        ),
    ]
