# Generated by Django 5.1.2 on 2024-11-16 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0011_alter_watchlist_user_alter_watchlist_unique_together"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="comment",
            new_name="content",
        ),
    ]
