# Generated by Django 5.1.2 on 2024-11-16 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0012_rename_comment_comment_content"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="comment_at",
            new_name="created_at",
        ),
    ]
