name: Backend Tests

on:
  push:
    branches: [main]
    paths:
      - "Project 4 network/network-backend/**"
  pull_request:
    branches: [main]
    paths:
      - "Project 4 network/network-backend/**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install --user django

      - name: Run Tests
        run: |
          cd "Project 4 network"
          cd network-backend
          python manage.py test
